# Generated by Django 6.0.4 on 2026-04-24 04:20

import apps.home.models
import autoslug.fields
import django.utils.timezone
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', apps.home.models.Title(help_text='Required', max_length=250, verbose_name='Title')),
                ('body', models.TextField()),
                ('quote', models.TextField(blank=True, max_length=1000, null=True)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1800, 1800], upload_to='articles/images/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title', unique_with=['created_at'])),
                ('is_feature', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'created_at')},
            },
        ),
    ]
