# Generated by Django 6.0.4 on 2026-04-26 01:18

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DR.', 'DR.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('MR.', 'MR.'), ('MRS.', 'MRS.'), ('Ms.', 'Ms.'), ('PROF.', 'PROF.'), ('REV.', 'REV.'), ('Rt. Hon.', 'Rt. Hon.'), ('SR.', 'SR.')], max_length=10)),
                ('position', models.CharField(blank=True, choices=[('CHAIRMAN', 'CHAIRMAN'), ('VICE CHAIR', 'VICE CHAIR'), ('SECRETARY', 'SECRETARY'), ('DEPUTY SECRETARY', 'DEPUTY SECRETARY'), ('ORGANISING SECRETARY', 'ORGANISING SECRETARY'), ('DEPUTY ORGANISING SECRETARY', 'DEPUTY ORGANISING SECRETARY'), ('TREASURER', 'TREASURER'), ('DEPUTY TREASURER', 'DEPUTY TREASURER'), ('EDITOR', 'EDITOR')], help_text=' Executive Committee Position', max_length=255, null=True, verbose_name='Executive Committee Position')),
                ('rank', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text=' Executive Rank', max_length=255, null=True, verbose_name='Executive Committee Rank')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle Name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('bio', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Bio')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Executive Committee Member Avatar', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery/executive/')),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executive',
            },
        ),
    ]
