# Generated by Django 6.0.4 on 2026-04-26 02:44

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_executive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DR.', 'DR.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('ESQ.', 'ESQ.'), ('HON.', 'HON.'), ('MR.', 'MR.'), ('MRS.', 'MRS.'), ('Ms.', 'Ms.'), ('PROF.', 'PROF.'), ('REV.', 'REV.'), ('Rt. Hon.', 'Rt. Hon.'), ('SR.', 'SR.')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle Name')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('position', models.CharField(blank=True, choices=[('EXECUTIVE DIRECTOR', 'EXECUTIVE DIRECTOR'), ('ASSISTANT ADMINISTRATOR', 'ASSISTANT ADMINISTRATOR'), ('SENIOR ICT OFFICER', 'SENIOR ICT OFFICER'), ('SECRETARY', 'SECRETARY'), ('EDITOR', 'EDITOR')], help_text='Secretariat Position', max_length=255, null=True, verbose_name='Secretariat Position')),
                ('rank', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='Secretariat Rank', max_length=255, null=True, verbose_name='Secretariat Rank')),
                ('bio', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Bio')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Secretariat Member Avatar', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery/secretariat/')),
            ],
            options={
                'verbose_name': 'Secretariat',
                'verbose_name_plural': 'Secretariat',
            },
        ),
    ]
