# Generated by Django 6.0.4 on 2026-04-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_secretariat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/executive/'),
        ),
        migrations.AlterField(
            model_name='secretariat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/secretariat/'),
        ),
    ]
