# Generated by Django 6.0.4 on 2026-04-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_executive_avatar_alter_secretariat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
    ]
