# Generated by Django 6.0.4 on 2026-04-27 00:07

import apps.home.models
import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_article_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Please add a short text about the banner ', max_length=75, null=True, verbose_name='Descriptive text')),
                ('top_banner', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery//uploads/%Y/%m/%d/')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload banner images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/uploads/%Y/%m/%d/')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery//uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('launched_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Launched On')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique_with=['launched_on'])),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', apps.home.models.Title(help_text='Required', max_length=250, verbose_name='Title')),
                ('body', models.TextField()),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[3648, 3648], upload_to='walk/images/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title', unique_with=['created_at'])),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='home.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_launched', models.DateTimeField(blank=True, null=True, verbose_name='Launched On ')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique_with=['year_launched'])),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Chapter banner ', keep_meta=True, null=True, quality=95, scale=None, size=[1080, 1080], upload_to='chapter/uploads/%Y/%m/%d/')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='home.faculty')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your image ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery/uploads/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, help_text='Please add a short alternative about the image', max_length=100, null=True, verbose_name='Alternative text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.article')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.chapter')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.event')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.home.models.Title(help_text='Required', max_length=250, verbose_name='Title')),
                ('relation', models.CharField(blank=True, help_text='Relation with UoNAA ', max_length=125, null=True, verbose_name='Partner Relation')),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[3648, 3648], upload_to='gallery/partners/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'created_at')},
            },
        ),
    ]
