# Generated by Django 6.0.4 on 2026-04-27 00:08

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_banner_faculty_event_department_chapter_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your image ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='gallery/image-uploads/%Y/%m/%d/'),
        ),
    ]
