# Generated by Django 6.0.4 on 2026-04-27 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='home.chapter'),
        ),
    ]
