# Generated by Django 6.0.4 on 2026-04-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_article_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
