# Generated by Django 6.0.4 on 2026-04-27 04:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_chapter_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload banner images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='top_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/top_banner/%Y/%m/%d/'),
        ),
    ]
