# Generated by Django 6.0.4 on 2026-04-27 04:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_banner_image_alter_banner_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[400, 400], upload_to='banner/logo/%Y/%m/%d/'),
        ),
    ]
