# Generated by Django 6.0.4 on 2026-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_banner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('article', 'Article'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('forum', 'Forum'), ('training', 'Training')], default='article', max_length=50, verbose_name='Article Type'),
        ),
    ]
