# Generated by Django 6.0.4 on 2026-04-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_article_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('svg_path', models.CharField(blank=True, help_text='SVG path data for the icon', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for this core value', null=True, upload_to='core_values/bg/')),
                ('background_color', models.CharField(default='#ffffff', help_text='Fallback background color (hex code)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'name'],
            },
        ),
    ]
