# Generated by Django 6.0.4 on 2026-04-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_corevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='svg_path',
            field=models.TextField(blank=True, help_text='SVG path data for the icon'),
        ),
    ]
