# Generated by Django 6.0.4 on 2026-05-01 20:58

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_banner_bottom_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='launched_on',
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name'),
        ),
    ]
