# Generated by Django 6.0.4 on 2026-05-01 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_faculty_launched_on_faculty_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier_type', models.CharField(choices=[('life', 'Life Member'), ('annual', 'Annual Member'), ('honorary', 'Honorary Member'), ('corporate', 'Corporate Partner')], max_length=20)),
                ('duration_months', models.IntegerField(default=0, help_text='0 = lifetime')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Other', 'Other')], max_length=10)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('maiden_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('id_passport_no', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(default='Kenyan', max_length=100)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone_mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?254\\d{9}$', message='Enter a valid Kenyan phone number (e.g., 2547XXXXXXXX)')])),
                ('phone_alt', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('student_reg_no', models.CharField(blank=True, max_length=50)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('is_lifetime_member', models.BooleanField(default=False)),
                ('membership_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('membership_card_issued', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_sent', models.BooleanField(default=False)),
                ('certificate_generated_at', models.DateTimeField(blank=True, null=True)),
                ('lapel_badge_issued', models.BooleanField(default=False)),
                ('receive_newsletter', models.BooleanField(default=True)),
                ('receive_sms_alerts', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
                ('current_membership_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.membershiptier')),
            ],
        ),
    ]
