# Generated by Django 6.0.4 on 2026-05-13 02:27

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_membershiptier_alumniprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='middle_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload your item images ', keep_meta=True, null=True, quality=95, scale=None, size=[1400, 1400], upload_to='banner/bottom_banner/%Y/%m/%d/'),
        ),
    ]
