# Generated by Django 6.0.4 on 2026-05-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_banner_middle_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
