# Generated by Django 6.0.4 on 2026-05-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/banners/'),
        ),
    ]
